// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_tpDPG5ZSk",
    "aws_user_pools_web_client_id": "19tqviu97olktc4k45ib7ff8p9"
};


export default awsmobile;
